//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A62CA8_myreturnEntities : DbContext
    {
        public DB_A62CA8_myreturnEntities()
            : base("name=DB_A62CA8_myreturnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AddBeneficiary> TB_AddBeneficiary { get; set; }
        public virtual DbSet<TB_BranchSendPayment> TB_BranchSendPayment { get; set; }
        public virtual DbSet<TB_ComplaintRegister> TB_ComplaintRegister { get; set; }
        public virtual DbSet<TB_ComplaintType> TB_ComplaintType { get; set; }
        public virtual DbSet<TB_CustomerWallet> TB_CustomerWallet { get; set; }
        public virtual DbSet<TB_Designation> TB_Designation { get; set; }
        public virtual DbSet<TB_MasterToken> TB_MasterToken { get; set; }
        public virtual DbSet<TB_MoneySenderDetails> TB_MoneySenderDetails { get; set; }
        public virtual DbSet<TB_OrderMoneyTransfer> TB_OrderMoneyTransfer { get; set; }
        public virtual DbSet<TB_PanCard> TB_PanCard { get; set; }
        public virtual DbSet<TB_PancardServiceRequest> TB_PancardServiceRequest { get; set; }
        public virtual DbSet<TB_Webhook> TB_Webhook { get; set; }
        public virtual DbSet<TB_AccountingDocument> TB_AccountingDocument { get; set; }
        public virtual DbSet<TB_AddPartner> TB_AddPartner { get; set; }
        public virtual DbSet<TB_AdminUser> TB_AdminUser { get; set; }
        public virtual DbSet<TB_AEPS_Commission_Chart> TB_AEPS_Commission_Chart { get; set; }
        public virtual DbSet<TB_AEPSServiceRequest> TB_AEPSServiceRequest { get; set; }
        public virtual DbSet<TB_AsignTask> TB_AsignTask { get; set; }
        public virtual DbSet<TB_AssignArea> TB_AssignArea { get; set; }
        public virtual DbSet<TB_AssignMenu> TB_AssignMenu { get; set; }
        public virtual DbSet<TB_AssignOrder> TB_AssignOrder { get; set; }
        public virtual DbSet<TB_BusinessIncome> TB_BusinessIncome { get; set; }
        public virtual DbSet<TB_CapitalIncome> TB_CapitalIncome { get; set; }
        public virtual DbSet<TB_City> TB_City { get; set; }
        public virtual DbSet<tb_Complaint> tb_Complaint { get; set; }
        public virtual DbSet<TB_Country> TB_Country { get; set; }
        public virtual DbSet<TB_DigitalSignature> TB_DigitalSignature { get; set; }
        public virtual DbSet<TB_DigitalSignatureDocument> TB_DigitalSignatureDocument { get; set; }
        public virtual DbSet<TB_DocumentApprove> TB_DocumentApprove { get; set; }
        public virtual DbSet<TB_Downloads> TB_Downloads { get; set; }
        public virtual DbSet<TB_DTHRechargeCommission> TB_DTHRechargeCommission { get; set; }
        public virtual DbSet<TB_Employee> TB_Employee { get; set; }
        public virtual DbSet<TB_FinalSubmission> TB_FinalSubmission { get; set; }
        public virtual DbSet<TB_GSTAndAccounting> TB_GSTAndAccounting { get; set; }
        public virtual DbSet<TB_GSTRelatedServices> TB_GSTRelatedServices { get; set; }
        public virtual DbSet<TB_GSTService> TB_GSTService { get; set; }
        public virtual DbSet<TB_GSTServiceDocument> TB_GSTServiceDocument { get; set; }
        public virtual DbSet<TB_HouseIncome> TB_HouseIncome { get; set; }
        public virtual DbSet<TB_HousingLoanBank> TB_HousingLoanBank { get; set; }
        public virtual DbSet<TB_IncomeTaxReturn> TB_IncomeTaxReturn { get; set; }
        public virtual DbSet<TB_ITR> TB_ITR { get; set; }
        public virtual DbSet<TB_ITROtherDocument> TB_ITROtherDocument { get; set; }
        public virtual DbSet<TB_LatestUpdate> TB_LatestUpdate { get; set; }
        public virtual DbSet<TB_Marketing> TB_Marketing { get; set; }
        public virtual DbSet<tb_MobileRecharge_Commission> tb_MobileRecharge_Commission { get; set; }
        public virtual DbSet<TB_Notification> TB_Notification { get; set; }
        public virtual DbSet<TB_OrderCompilation> TB_OrderCompilation { get; set; }
        public virtual DbSet<TB_OrderDiscussion> TB_OrderDiscussion { get; set; }
        public virtual DbSet<TB_OrderPayment> TB_OrderPayment { get; set; }
        public virtual DbSet<TB_OtherServices> TB_OtherServices { get; set; }
        public virtual DbSet<TB_Pages> TB_Pages { get; set; }
        public virtual DbSet<TB_PartnerDocument> TB_PartnerDocument { get; set; }
        public virtual DbSet<TB_PartnerProfile> TB_PartnerProfile { get; set; }
        public virtual DbSet<TB_PartnerTask> TB_PartnerTask { get; set; }
        public virtual DbSet<TB_PayoutCharges> TB_PayoutCharges { get; set; }
        public virtual DbSet<TB_PreorPostpaid> TB_PreorPostpaid { get; set; }
        public virtual DbSet<TB_Profession> TB_Profession { get; set; }
        public virtual DbSet<TB_RegistrationStatus> TB_RegistrationStatus { get; set; }
        public virtual DbSet<TB_SalaryIncome> TB_SalaryIncome { get; set; }
        public virtual DbSet<TB_ServiceOrder> TB_ServiceOrder { get; set; }
        public virtual DbSet<TB_ServiceOrderBank> TB_ServiceOrderBank { get; set; }
        public virtual DbSet<TB_ServiceOrderDeduction> TB_ServiceOrderDeduction { get; set; }
        public virtual DbSet<TB_ServiceOrderDocument> TB_ServiceOrderDocument { get; set; }
        public virtual DbSet<TB_ServiceOrderIncome> TB_ServiceOrderIncome { get; set; }
        public virtual DbSet<TB_ServiceOrderSubmission> TB_ServiceOrderSubmission { get; set; }
        public virtual DbSet<TB_ServicePackage> TB_ServicePackage { get; set; }
        public virtual DbSet<TB_ServicePrice> TB_ServicePrice { get; set; }
        public virtual DbSet<TB_State> TB_State { get; set; }
        public virtual DbSet<TB_Tahsils> TB_Tahsils { get; set; }
        public virtual DbSet<TB_TradingIncome> TB_TradingIncome { get; set; }
        public virtual DbSet<TB_Trash> TB_Trash { get; set; }
        public virtual DbSet<tb_TravelCommission> tb_TravelCommission { get; set; }
        public virtual DbSet<TB_UpdateForPartner> TB_UpdateForPartner { get; set; }
        public virtual DbSet<TB_UserServicePackage> TB_UserServicePackage { get; set; }
        public virtual DbSet<TB_UTIPAN> TB_UTIPAN { get; set; }
        public virtual DbSet<tb_walletdeduction> tb_walletdeduction { get; set; }
        public virtual DbSet<TB_Registration> TB_Registration { get; set; }
        public virtual DbSet<AEPSHistory> AEPSHistories { get; set; }
        public virtual DbSet<TB_AEPSHistory> TB_AEPSHistory { get; set; }
        public virtual DbSet<TB_Recharge> TB_Recharge { get; set; }
        public virtual DbSet<TB_CallBackUPI> TB_CallBackUPI { get; set; }
        public virtual DbSet<TB_InternalWalletTransfer> TB_InternalWalletTransfer { get; set; }
        public virtual DbSet<TB_Pay2AllTransactionHistory> TB_Pay2AllTransactionHistory { get; set; }
        public virtual DbSet<TB_WalletDeductionHistory> TB_WalletDeductionHistory { get; set; }
        public virtual DbSet<TB_ZuelPay> TB_ZuelPay { get; set; }
        public virtual DbSet<TB_UPICollect> TB_UPICollect { get; set; }
    }
}
