//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AssignMenu
    {
        public long Assign_Id { get; set; }
        public Nullable<long> Emp_Id { get; set; }
        public Nullable<long> Page_Id { get; set; }
    }
}
