//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AddBeneficiary
    {
        public long BeneficiaryId { get; set; }
        public long SenderId { get; set; }
        public long RetailerId { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string BankIfsc { get; set; }
        public string BeneficiaryName { get; set; }
        public string MobileNumber { get; set; }
    }
}
