//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AEPSServiceRequest
    {
        public long AEPSId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> ReuestDate { get; set; }
        public string Status { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string MemberId { get; set; }
        public string ProcessBy { get; set; }
        public string ProcessByCode { get; set; }
    }
}
