//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AEPSHistory
    {
        public long AepsId { get; set; }
        public long status_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string utr { get; set; }
        public string report_id { get; set; }
        public string number { get; set; }
        public Nullable<long> payment_id { get; set; }
        public string outlet_id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<decimal> DistributorCommision { get; set; }
        public Nullable<decimal> RetailerCommision { get; set; }
    }
}
