//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AsignTask
    {
        public long AsignTaskID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<long> TaskAssignEmployeeID { get; set; }
    }
}
