//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AssignOrder
    {
        public long AssignOrderId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string AssignStatus { get; set; }
        public string Remarks { get; set; }
    }
}
