//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AEPS_Commission_Chart
    {
        public long AEPSId { get; set; }
        public Nullable<long> AEPS_SLABSFrom { get; set; }
        public Nullable<long> AEPS_SLABSTo { get; set; }
        public Nullable<decimal> ThirdPartyFrom { get; set; }
        public Nullable<decimal> ThirdPartyTo { get; set; }
        public Nullable<decimal> Distributor { get; set; }
        public Nullable<decimal> Retailer { get; set; }
        public Nullable<decimal> ProfitFrom { get; set; }
        public Nullable<decimal> ProfitTo { get; set; }
    }
}
