//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AddPartner
    {
        public long PartnerId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string PartnerName { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> ReferDate { get; set; }
        public string ReferStatus { get; set; }
        public string ReferBy { get; set; }
        public string RefCode { get; set; }
    }
}
