//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BranchSendPayment
    {
        public long PaymentId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentFor { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string UploadFile { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentType { get; set; }
        public string RejectReason { get; set; }
        public string PaymentBy { get; set; }
        public string PaymentByCode { get; set; }
    }
}
