//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CustomerWallet
    {
        public long WalletId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<decimal> WalletAmount { get; set; }
        public Nullable<decimal> MainWallet { get; set; }
        public Nullable<decimal> TreadWallet { get; set; }
    }
}
