//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Complaint
    {
        public long ComplaintId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ServiceName { get; set; }
        public string CustemerId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Complaint { get; set; }
        public string status { get; set; }
        public string Processed_by { get; set; }
        public string Message { get; set; }
    }
}
