//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CallBackUPI
    {
        public int id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string payid { get; set; }
        public string client_id { get; set; }
        public string operator_ref { get; set; }
        public string number { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string virtual_account_number { get; set; }
        public string name { get; set; }
    }
}
