//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CapitalIncome
    {
        public long CapitalIncomeId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string NameOfProperty { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public string AmountOfSale { get; set; }
        public string AttachmentOfSale { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchaseAmount { get; set; }
        public string AttachmentOfPurchase { get; set; }
        public string Remarks { get; set; }
        public string OtherRemarks { get; set; }
    }
}
