//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DigitalSignature
    {
        public long DigitalId { get; set; }
        public string DigitalType { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string CustomerName { get; set; }
        public string cEmail { get; set; }
        public Nullable<System.DateTime> cDOB { get; set; }
        public string cMobileNumber { get; set; }
        public string ServiceNo { get; set; }
        public string ServiceStatus { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    }
}
