//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Employee
    {
        public long EmployeeId { get; set; }
        public string EmployeeFirstName { get; set; }
        public string EmployeeLastName { get; set; }
        public string UserName { get; set; }
        public string LoginPassword { get; set; }
        public string EmployeeAddress { get; set; }
        public Nullable<long> EmployeeMobileNumber { get; set; }
        public string EmployeeEmailID { get; set; }
        public Nullable<long> EmployeeDesignationID { get; set; }
        public Nullable<System.DateTime> EmployeeBirthdate { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeeCode { get; set; }
        public string UserType { get; set; }
        public string UserStatus { get; set; }
    }
}
