//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FinalSubmission
    {
        public long OrderSubmissionId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<decimal> ExtraAmountPaid { get; set; }
        public string Remarks { get; set; }
        public string PropertyMoreThan30Lac { get; set; }
        public string PropertyPurchaseMoreThan30Lac { get; set; }
        public string depositMorethan10lac { get; set; }
        public string appliedForIPO { get; set; }
        public string AnyCreditCard { get; set; }
        public string AntAdvTax { get; set; }
        public string BalanceSheet { get; set; }
    }
}
