//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GSTServiceDocument
    {
        public long DocumentId { get; set; }
        public Nullable<long> GSTId { get; set; }
        public string DocumentName { get; set; }
        public string UploadedDocument { get; set; }
        public string UserId { get; set; }
        public string DocumentPassword { get; set; }
    }
}
