//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITR
    {
        public long ITRId { get; set; }
        public string ITRType { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string FinancialYear { get; set; }
        public string CustomerName { get; set; }
        public string cCEmail { get; set; }
        public Nullable<System.DateTime> cDOB { get; set; }
        public string cMobileNumber { get; set; }
        public string AccountNumber { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string PancardName { get; set; }
        public string PanCardNumber { get; set; }
        public string PanPassword { get; set; }
        public string PancardImage { get; set; }
        public string NameOnAdharCard { get; set; }
        public string AdharcardNumber { get; set; }
        public string AdharcardImage { get; set; }
        public string UploadForm16 { get; set; }
        public string UploadPaymentSlip { get; set; }
        public string ITRStatus { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string ITRNo { get; set; }
    }
}
