//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_InternalWalletTransfer
    {
        public long TransferId { get; set; }
        public Nullable<long> RegisterId { get; set; }
        public string FromWallet { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Desciption { get; set; }
    }
}
