//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ITROtherDocument
    {
        public long DocumentId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public Nullable<long> ITRId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
    }
}
