//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MobileRecharge_Commission
    {
        public long ServiceProviderId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> Retailer { get; set; }
        public Nullable<decimal> Distributor { get; set; }
        public Nullable<decimal> ThirdParty { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<int> PrepostId { get; set; }
    }
}
