//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OrderDiscussion
    {
        public long DiscussionId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> DiscussionDate { get; set; }
        public string Attachment { get; set; }
        public string Title { get; set; }
        public string DocumentName { get; set; }
        public string MsgBy { get; set; }
    }
}
