//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OrderMoneyTransfer
    {
        public long OrderTransferId { get; set; }
        public Nullable<System.DateTime> TransferDateTime { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string Sender { get; set; }
        public string Beneficiry { get; set; }
        public string Accountno { get; set; }
        public string Amount { get; set; }
        public Nullable<decimal> Servicecharge { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string BankRefNo { get; set; }
        public Nullable<decimal> retailerCharges { get; set; }
        public Nullable<decimal> retailerCommission { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<decimal> OpenBalance { get; set; }
        public Nullable<decimal> CloseBalance { get; set; }
        public string ProcessBy { get; set; }
        public string ProcessByCode { get; set; }
        public string AdminStatus { get; set; }
        public Nullable<long> SenderId { get; set; }
        public Nullable<long> RetailerId { get; set; }
        public string ReportId { get; set; }
        public string Message { get; set; }
        public Nullable<long> Client_Id { get; set; }
        public string Utr { get; set; }
        public string MobileNumber { get; set; }
        public string IFSC { get; set; }
    }
}
