//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PartnerTask
    {
        public long TaskId { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public string TaskTitle { get; set; }
        public string TaskMessage { get; set; }
        public string TaskStatus { get; set; }
    }
}
