//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PartnerProfile
    {
        public long ProfileId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string AccountHolderName { get; set; }
        public string BankName { get; set; }
        public string IDSCCode { get; set; }
        public string NameOnPancard { get; set; }
        public string PanCardNumber { get; set; }
        public string PancardDocument { get; set; }
        public string NameOnAdharcard { get; set; }
        public string AdharcardNumber { get; set; }
        public string AdharCardFront { get; set; }
        public string AdharCardBack { get; set; }
        public Nullable<System.DateTime> ProfileUpdateDate { get; set; }
        public string AccountNumber { get; set; }
    }
}
