//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PayoutCharges
    {
        public long PayoutId { get; set; }
        public Nullable<long> Payout_SLABSFrom { get; set; }
        public Nullable<long> Payout_SLABSTo { get; set; }
        public Nullable<decimal> ThirdPartyCharges { get; set; }
        public Nullable<decimal> Distributor { get; set; }
        public Nullable<decimal> Retailer { get; set; }
        public Nullable<decimal> Profit { get; set; }
    }
}
