//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Recharge
    {
        public long OrderId { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string CustomerMobile { get; set; }
        public Nullable<long> OperatorCode { get; set; }
        public string OperatorName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> RechargeAmount { get; set; }
        public Nullable<decimal> CommissionAmt { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public string PaymentType { get; set; }
        public string TransactionId { get; set; }
        public string RechargeType { get; set; }
        public string RechargeStatus { get; set; }
        public string OrderType { get; set; }
        public Nullable<decimal> OpenBalance { get; set; }
        public Nullable<decimal> CloseBalance { get; set; }
        public string ReportId { get; set; }
        public string Message { get; set; }
        public Nullable<long> Client_Id { get; set; }
        public string Utr { get; set; }
        public Nullable<decimal> RetailerCommision { get; set; }
        public Nullable<decimal> DistributorCommision { get; set; }
    }
}
