//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Registration
    {
        public long RegistrationId { get; set; }
        public string MobileNo { get; set; }
        public string LoginPassword { get; set; }
        public string FullName { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> ProfessionId { get; set; }
        public string ProfileImageName { get; set; }
        public string ProfilePhoto { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<System.DateTime> OTPEntryTime { get; set; }
        public Nullable<long> RegStatusId { get; set; }
        public string LoginId { get; set; }
        public string BranchCode { get; set; }
        public string ShopPhoto { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<long> TahsilsId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string MemberType { get; set; }
        public string Gender { get; set; }
        public string Pincode { get; set; }
        public string RefCode { get; set; }
        public string OutlateId { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress1 { get; set; }
        public string ShopAddress2 { get; set; }
        public string ShopCategory { get; set; }
        public string ShopPincode { get; set; }
        public string ShopPostOffice { get; set; }
        public string ShopAreaLocality { get; set; }
        public string OutlateIdStatus { get; set; }
        public string Adhar_Number { get; set; }
        public string Pan_Number { get; set; }
        public string Adhar_Front_Image { get; set; }
        public string Adhar_Back_Image { get; set; }
        public string Pan_Card_Image { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Account_Number { get; set; }
        public string Account_Holder_Name { get; set; }
        public string IFSC_Code { get; set; }
        public string Account_Type { get; set; }
        public string Bank_Address { get; set; }
        public string CancelledChequePhoto { get; set; }
        public string CancelledChequeName { get; set; }
        public Nullable<long> DId { get; set; }
        public Nullable<long> ADId { get; set; }
        public string PanAgentId { get; set; }
        public string BankDoc { get; set; }
        public Nullable<long> ShopCity { get; set; }
        public Nullable<long> ShopState { get; set; }
        public Nullable<long> ShopNo { get; set; }
        public string PostOffice { get; set; }
        public string DistributorCode { get; set; }
        public string DistributorId { get; set; }
    }
}
