//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ServiceOrder
    {
        public long OrderId { get; set; }
        public string ServiceYear { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string PanNo { get; set; }
        public string AdharNumber { get; set; }
        public string Gender { get; set; }
        public string HouseNo { get; set; }
        public string BuildingName { get; set; }
        public string RoadName { get; set; }
        public string Area { get; set; }
        public Nullable<long> CountryId { get; set; }
        public Nullable<long> StateId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string Pincode { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string AlternateMobile { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string OtherInformation { get; set; }
        public string OrderStatus { get; set; }
        public string ServiceName { get; set; }
        public string ServiceType { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> TahsilsId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PatnerName { get; set; }
        public string FirmName { get; set; }
    }
}
