//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TradingIncome
    {
        public long TradingIncomeId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public string OrderNumber { get; set; }
        public string BrokerName { get; set; }
        public string TotalSalesAmount { get; set; }
        public string TotalPurchaseAmount { get; set; }
        public string TradingStatement { get; set; }
        public string FinancialStatement { get; set; }
    }
}
