//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UpdateForPartner
    {
        public long UpdateId { get; set; }
        public string UpdateFor { get; set; }
        public string Attachment { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateTitle { get; set; }
    }
}
