//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UPICollect
    {
        public long Id { get; set; }
        public Nullable<decimal> client_id { get; set; }
        public Nullable<int> provider_id { get; set; }
        public string upi_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string note { get; set; }
        public Nullable<int> status_id { get; set; }
        public string message { get; set; }
        public string order_id { get; set; }
        public string payment_status { get; set; }
        public Nullable<long> RegistrationId { get; set; }
    }
}
