//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UserServicePackage
    {
        public long UserPackageId { get; set; }
        public string ServiceType { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
