//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Webhook
    {
        public long Wid { get; set; }
        public Nullable<long> status_id { get; set; }
        public string utr { get; set; }
        public string report_id { get; set; }
        public Nullable<long> client_id { get; set; }
        public string number { get; set; }
    }
}
