//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalajiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_walletdeduction
    {
        public long id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string Reason { get; set; }
        public Nullable<long> RegistrationId { get; set; }
        public Nullable<System.DateTime> DeductionDate { get; set; }
        public string Processed_by { get; set; }
        public string ServiceName { get; set; }
    }
}
